### PR TITLE
update alectryon

### PR DESCRIPTION
**Pull request by Alizter**

### CODE REVIEW

**Comment by JasonGross** [comment]
> @JasonGross
> 
> ```
>  File "/github/workspace/etc/alectryon/alectryon/cli.py", line 419, in <lambda>
>     write_output(ext, contents, fname, fpath, output, output_directory, coq_args_Q, coq_args_R, strip_re=strip_re)
> ...
> TypeError: write_output() got multiple values for argument 'strip_re'
> ```

Thanks, fixed this one, restarted job

**Comment by jdchristensen** [comment]
It said that there were no artifacts, so I tried restarting all jobs.

**Comment by jdchristensen** [comment]
@JasonGross Still getting a similar error.

**Comment by Alizter** [comment]
@jdchristensen I needed to update the submodule again to the updated version of Jason's branch. Let's see if this works.

**Review by JasonGross — APPROVED** [review]
It passes!

**Pull request merged**
