### PR TITLE
remove 8.15 compat

### PR DESCRIPTION
**Pull request by Alizter**
We had some compat code leftover.

### CODE REVIEW

**Comment by jdchristensen** [comment]
Does this mean it won't build with 8.15 anymore?  Maybe we should keep compatibility until we have a strong reason to not be compatible, as some users might not have upgraded to 8.16.

**Comment by jdchristensen** [comment]
Well, even after #1661, the library should still be usable with 8.15.  I would prefer to delay removing the compatibility code until we have merged something else that prevents the library from being used with 8.15.  8.16 was only released a week ago...

**Comment by Alizter** [comment]
@jdchristensen As you wish, this PR does no harm sitting here.

**Comment by Alizter** [comment]
@jdchristensen Since #1697 is going to use 8.16 features, I think we should merge this.

**Comment by jdchristensen** [comment]
I agree.  LGTM.

**Pull request merged**
