### PR TITLE
Remove unused Require commands

### PR DESCRIPTION
**Pull request by jdchristensen**
As discussed in #1242, one idea for speeding up compilation of the library is to get rid of `Require` commands that aren't needed.  A while back I tried using @JasonGross 's minimize-requires script, but I couldn't get it to work on the HoTT library (see JasonGross/coq-tools#123).  So I wrote my own script.

The first commit in this PR is entirely generated by the script.  It found 718 Require'd files that can be removed.  The subsequent three commits manually adjust four files.

Unfortunately, this doesn't make as much of a difference as I hoped.  For `make theories/HoTT.vo`, the time is reduced by 3.6% with -j8 and 0.9% with -j1.  For `make`, the time is reduced by 1.5% with -j8, and I didn't bother testing -j1.  I checked that no single file got significantly slower (except for one that is fixed in the second commit).

I think one reason that the speed didn't improve that much is that many of the things we `Require` are transitive dependencies via another file, so getting rid of the `Require` doesn't save much time or give additional parallelization.

Still, it's probably worth having unnecessary things removed, so I am making this PR.

Question:  The script checks things of the form `Require Foo` and `Require Import Foo` (but leaves `Require Export Foo` alone).  I noticed that there were many "meta" files in the Categories folder that use `Require Foo` similarly to how the rest of the library uses `Require Export Foo`, e.g. `Categories.v` and `Categories/Adjoint.v`.  I manually excluded these files from the processing.  (I'll put the full list in the next comment.)  However, there were other files that had `Require Foo`, and I eliminated those if they were not needed.  Is this correct?  For examples, look at `Categories/Adjoint/Pointwise.v`, `Categories/Comma/Functorial.v`, `Categories/ExponentialLaws/Law3/Functors.v`, etc.

It's easy for me to re-run the script if needed.  It takes 5m30s to check every `Require`d file in the whole library.

### CODE REVIEW

**Comment by jdchristensen** [comment]
Here are the files that the script excludes:
```
    'theories/Categories.v',
    'theories/Categories/Adjoint.v',
    'theories/Categories/Adjoint/Composition.v',
    'theories/Categories/Adjoint/Notations.v',
    'theories/Categories/Adjoint/Functorial.v', # breaks Categories/Adjoint.v
    'theories/Categories/Category.v',
    'theories/Categories/Category/Notations.v',
    'theories/Categories/Category/Sigma.v',
    'theories/Categories/Comma.v',
    'theories/Categories/ExponentialLaws.v',
    'theories/Categories/ExponentialLaws/Law1.v',
    'theories/Categories/ExponentialLaws/Law2.v',
    'theories/Categories/ExponentialLaws/Law3.v',
    'theories/Categories/ExponentialLaws/Law4.v',
    'theories/Categories/Functor.v',
    'theories/Categories/Functor/Composition.v',
    'theories/Categories/Functor/Composition/Functorial.v',
    'theories/Categories/Functor/Notations.v',
    'theories/Categories/Functor/Pointwise.v',
    'theories/Categories/Functor/Prod.v',
    'theories/Categories/FunctorCategory.v',
    'theories/Categories/FunctorCategory/Notations.v',
    'theories/Categories/Grothendieck.v',
    'theories/Categories/Grothendieck/ToSet.v',
    'theories/Categories/GroupoidCategory.v',
    'theories/Categories/InitialTerminalCategory.v',
    'theories/Categories/KanExtensions.v',
    'theories/Categories/LaxComma.v',
    'theories/Categories/Limits.v',
    'theories/Categories/NaturalTransformation.v',
    'theories/Categories/NaturalTransformation/Composition.v',
    'theories/Categories/NaturalTransformation/Dual.v',
    'theories/Categories/NaturalTransformation/Notations.v',
    'theories/Categories/Notations.v',
    'theories/Categories/Profunctor.v',
    'theories/Categories/Profunctor/Notations.v',
    'theories/Categories/Pseudofunctor.v',
    'theories/Categories/SetCategory.v',
    'theories/Categories/Structure.v',
    'theories/Categories/Utf8.v',
    'theories/Classes/tests/ring_tac.v',        # slow, and nothing changes
    'theories/Classes/interfaces/integers.v',   # only a comment changes
```

**Comment by JasonGross** [comment]
> However, there were other files that had `Require Foo`, and I eliminated those if they were not needed. Is this correct?

Yes, as long as removing the `Require`/`Require Import ` does not change the meaning of any overloaded notation that gets used in the file.  (I'm guessing it's all good, since I don't think there are any cases of potentially ambiguous notation that without further definitions requiring one meaning)

**Comment by jdchristensen** [comment]
It case anyone is interested, I have attached the python3 script here: [coqcstripimports.txt](https://github.com/HoTT/Coq-HoTT/files/10333074/coqcstripimports.txt)  (Save and rename to remove the `.txt` extension.)

It's a wrapper for `coqc`, so you can invoke it properly by using `make`.  An example is below.

BTW, it removes almost 23% of all Required files!

```
$ chmod a+rx ~/bin/coqcstripimports
$ export COQC=~/bin/coqcstripimports
$ make clean > /dev/null

$ # A first example:
$ make -j1 theories/Basics/Numeral.vo
bash etc/generate_coqproject.sh
coq_makefile -f _CoqProject -o Makefile.coq
make --no-print-directory -f Makefile.coq theories/Basics/Numeral.vo
COQDEP VFILES
*** Warning: in file theories/Basics/Notations.v, declared ML module ltac_plugin has not been found!
*** Warning: in file theories/Basics/Overture.v, declared ML module number_string_notation_plugin has not been found!
COQC theories/Basics/Notations.v
COQC theories/Basics/Logic.v
COQC theories/Basics/Datatypes.v
--- 1 attempts made to theories/Basics/Datatypes.v
COQC theories/Basics/Overture.v
COQC theories/Basics/Decimal.v
--- 1 attempts made to theories/Basics/Decimal.v
COQC theories/Basics/Hexadecimal.v
--- 2 attempts made to theories/Basics/Hexadecimal.v
COQC theories/Basics/Numeral.v
--- 2 changes made to theories/Basics/Numeral.v <<<<<<<<<<<<<<
--- 3 attempts made to theories/Basics/Numeral.v

$ git diff theories/Basics/Numeral.v | cat
diff --git a/theories/Basics/Numeral.v b/theories/Basics/Numeral.v
index d04d523b..38810190 100644
--- a/theories/Basics/Numeral.v
+++ b/theories/Basics/Numeral.v
@@ -1,4 +1,4 @@
-Require Import Basics.Overture Basics.Decimal Basics.Hexadecimal.
+Require Import Basics.Hexadecimal.
 
 (** * Decimal or Hexadecimal numbers *)
 
$ git restore .
$ make clean > /dev/null
$ # Do a full run; choose -jJ to suit your machine:
$ time make -j8 2>&1
[output omitted]
real	5m22.477s
```

**Comment by jdchristensen** [comment]
I'll be pushing an improved version of this PR soon.

**Comment by Alizter** [comment]
@jdchristensen Really great stuff! I think it would be a good idea to include your script in `etc/` for future use by the way. You should probably give it a `.py` extension.

**Comment by jdchristensen** [comment]
I force pushed a new set of three commits.  The first removes commented out Require commands that confuse the script.  The second is a new set of automated changes.  And the third removes unneeded changes to the Warnings.

The script had two bugs which caused it to not eliminate some Required files that weren't needed.  I fixed those bugs.  Also, I added a feature that times the builds, and rejects changes that slow it down.  (It's allowed to get 0.01s or 3% slower, to allow for fluctuations in the timing.)  This didn't affect much besides the slowdown to PullbackFiberSequence that I already mentioned above.

The new script attempted 3182 changes and kept 732 of them, around 23%.  16 were excluded for timing reasons, but many of those would probably have failed with an error after a slow typeclass search, or something like that.

If some of the changes lead to problems in the future, we can of course re-add the Require commands as needed.

I will upload the new script after some clean-up.

**Comment by jdchristensen** [comment]
I found one more thing to drop, and also have included the script in `etc/coqcstriprequires.py`.  I think this can be merged if others think it is ok.

**Comment by Alizter** [comment]
@jdchristensen I want to take a closer look at the changes to see if anything seems off. After that, I will merge.

**Comment by jdchristensen** [comment]
Rebased.

**Review by Alizter — APPROVED** [review]
LGTM. I woldn't mind a comment from @mikeshulman who has in the past expressed a distaste for removing `Require Import Basics Types` from a file. If we get no answer, I will go ahead and merge.

**Comment by jdchristensen** [comment]
I have another PR that builds on this one ready to go, but I'll wait to see what happens here before opening it.  The other one speeds up the -j8 build by 15%, just by making Require commands more refined, to allow more parallelization.

**Comment by Alizter** [comment]
@jdchristensen That is excellent news. Since we can always revert, I will go ahead an merge this PR.

**Comment by mikeshulman** [comment]
I probably still have a distaste for removing `Require Import Basics Types`, but since I'm not really using this library any more, my opinion doesn't carry much weight.

**Comment by jdchristensen** [comment]
@Alizter Did you squash the commits?  That makes it harder for me to make my next PR, since they were based off of the original commits.  Also, I had carefully broken up the process into logical chunks.  If we revert, can we redo it as usual?  If not, I'll figure out how to cherry-pick my new material to the new head.

**Comment by jdchristensen** [comment]
@mikeshulman I was also hesitant, but when I continued on with looking for where unneeded dependencies were lurking, it was quite helpful to have minimal Requires lines to sort through.

BTW, is there another library you are focusing on?

**Comment by jdchristensen** [comment]
@Alizter No, I don't think reverting will work, as it just adds a further commit reverting the previous one.  I'll figure out how to fix up my branch.

**Comment by mikeshulman** [comment]
Right now I'm less interested in Book HoTT and more focused on developing H.O.T.T.  Once the foundations of that are in order and published, then I'll probably be thinking about implementations of it in proof assistants.  (Actually I've already played around a bit with toy implementations of HOTT in Agda using rewrite rules, but that's not really workable for large-scale projects.)

**Comment by mikeshulman** [comment]
Re: undoing a merge, can't you force-push to the master branch?

**Comment by jdchristensen** [comment]
@mikeshulman Cool!  I think it would be really nice to work in a system that avoids some of the awkwardness of Book HoTT.  Looking forward to seeing how it develops.  When you get to the stage of porting things over, I'd be happy to help.

About undoing the merge:  can I really just delete the merge locally and directly push to the master branch of the github repo?  That could cause others trouble, but maybe only Ali has pulled?

**Comment by mikeshulman** [comment]
That's great!

I'm pretty sure you *can* do that.  I agree it might cause problems for anyone who pulled in the last hour, but we can hope that there aren't many.

**Comment by jdchristensen** [comment]
Ok, I just force pushed, and will try to redo things.

**Comment by jdchristensen** [comment]
It all worked smoothly.  @Alizter , you might need to do something like `git reset --hard HEAD~1` before you pull again (assuming that the merge commit you made is the last commit you have on the master branch).

**Comment by mikeshulman** [comment]
By the way, for future reference, the reason for my distaste for removing `Basics` and `Types` is that the stuff in there is so fundamental that I expect it to be present all the time.  I find it surprising, annoying, and sometimes even confusing if I'm adding new code to an existing file and I try to use some basic fact and discover that it wasn't imported and I have to go back up to the top of the file and add a new `Require` before I can use it.

In general, I think that `Require` lines should strike a balance between importing only what is strictly needed for the present contents of a file to compile and supplying the background that might reasonably be expected to be wanted by future authors of additions to that file.  My inclination would be to put `Basics` and `Types` on the second side of that balance.  But, as I said, my opinion doesn't carry much weight with this library right now.

**Comment by Alizter** [comment]
> @Alizter Did you squash the commits? That makes it harder for me to make my next PR, since they were based off of the original commits. Also, I had carefully broken up the process into logical chunks. If we revert, can we redo it as usual? If not, I'll figure out how to cherry-pick my new material to the new head.

Yes. Looks like at some point this became the default merge option for me. I must have changed it unknowingly a while back.

> It all worked smoothly. @Alizter , you might need to do something like git reset --hard HEAD~1 before you pull again (assuming that the merge commit you made is the last commit you have on the master branch).

I didn't squash locally, only through Github so it won't be a problem for me.

Thanks Mike for your comments by the way.

**Comment by jdchristensen** [comment]
@mikeshulman I agree completely with what you wrote.  I should have left `Basics` and `Types` in place, at least in "higher level" sections of the library.  Once you are using truncations, say, there is no advantage to not Requiring Basics and Types.  I'll see if I can make a further PR that restores some of them.

OTOH, I think that most or maybe all of the changes in #1694 that replace Basics and Types with subsets are appropriate.  This was done in "low level" sections of the library, like Types, WildCat and Categories.  WildCat in particular uses surprisingly little of Basics and Types, and many other things depend on WildCat, so I think it's a reasonable compromise to use more specific Require commands in those parts.

**Comment by jdchristensen** [comment]
> I should have left `Basics` and `Types` in place, at least in "higher level" sections of the library. Once you are using truncations, say, there is no advantage to not Requiring Basics and Types. I'll see if I can make a further PR that restores some of them.

@mikeshulman I took a look through the changes, and I think that almost everywhere that removed `Basics` and `Types` still have them in the namespace.  This is because of the file `Classes/interfaces/canonical_names.v`, which has `Require Export HoTT.Basics HoTT.Types HoTT.Truncations.`  Other files `Require Export` that file, and that continues to various files including `Group.v` and `AbelianGroup.v`.  So I'm not going to do a further PR to restore those `Require` commands.  If any places are found where they are truly missing, they can be added as needed.

**Comment by mikeshulman** [comment]
Okay, thanks!

Do we have a general policy for when to `Require Export`?

**Comment by jdchristensen** [comment]
> Do we have a general policy for when to Require Export?

I was thinking of asking *you* that!  I was surprised that this was done in canonical_names.v, and also that Truncations was required for that and everything that requires it.

AbelianGroup.v used to Export Group.v, but I changed it to be a bit more selective, and this lead me to add similar selective Exports elsewhere. E.g. AbPullback now Exports Groups.GrpPullback (because other files that imported AbPullback were expecting this to be present).  (The meta-file AbGroups.v still Exports the meta-file Groups.v, and most users will just import AbGroups.v, so these changes are mainly internal to the AbGroups directory.)

I guess if FileA Requires material from FileB as an auxiliary tool, then Import is natural.  While if FileA builds on FileB in a way that you would almost always want FileB imported as well, then FileA could Export FileB.  But it's certainly a judgement call.

(Of course, our meta-files that Export (almost) everything in a directory use Exports.)

**Comment by mikeshulman** [comment]
Yeah, that makes sense.  For instance, `Modality` exports `ReflectiveSubuniverse`.

In general I think we are pretty sparse with re-exports.  Probably `canonical_names` does it surprisingly because that was part of the code that was imported from mathclasses, which was written with a different style.

**Pull request merged**
